[versions]
kotlin = "2.3.0"

log4j = "2.25.3"
gson = "2.13.2"

[libraries]
log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

[plugins]